### PR TITLE
Feature

### PR DESCRIPTION
**Pull request by HanningtoneM**

### CODE REVIEW

**Review by nicupop729 — CHANGES_REQUESTED** [review]
# STATUS: Required Changes ♻️

Hi @HanningtoneM, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!



### Some highlights for you
* Correct GitHub flow practice ✔️ 

### Required Changes ♻️

- [ ] Kindly, write a meaningful title for your pull request. "Feature" is not meaningful enough to represent the changes brought with this pull request to your project; For example, you can have it something like: "Build Hello World" or "Create an HTML file and style the project with CSS" etc
- [ ]  Always add a short summary of changes introduced in the pull request.
- [ ] Please refer to this article: please read it and apply it in your work from now on: [Professional repo - basic rules](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md);
- [ ] Kindly, correct the linters path to your project. In the root project, you need to have a folder named `.github`. Inside this one, you need another folder named `workflows`. And inside the `workflows` folder, you need a file named `linters.yml`. Inside this file, you need to have the linters. The linters needed for this project can be found [here](https://github.com/microverseinc/linters-config/tree/master/html-css);
- [ ] Kindly add the `test.md` file;
- [ ] Please add the `README.md` file with all it's sections; the template is [here](https://github.com/microverseinc/readme-template);
- [ ] Kindly, add your HTML and CSS files with a minimum style to pass the linters and with the simple text of Hello World;
- [ ] In order to respect project requirements, please, add back the `.gitignore` file with the following: `node_modules/` and `test.md` as they need to be ignored by git and not reach to GitHub repo;
- [ ] In order to merge the branches after approval, we are allowed to have conflicts between branches; Kindly, fix the conflicts;

- [ ] _Check the comments under the review._


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

- [ ] As we need to use descriptive names for our branches (e.g., refactor-authentication, user-content-cache-key, make-retina-avatars), kindly, change the name of the branch with something more meaningful as for example: 'build_project' or 'build_Hello_World' etc


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by HanningtoneM** [comment]
i have merged the branches and solved all the  requirements on my main branch

**Comment by HanningtoneM** [comment]
please have a look at the main branch

**Comment by topeogunleye** [comment]
> * Kindly, add your HTML and CSS files with a minimum style to pass the linters and with the simple text of Hello World;

You're not to merge any branches until your pull request is approved.

**Review by topeogunleye — COMMENTED** [review]
Hi @HanningtoneM,

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Invalid Code Review Request ⚠️

   - You have suHi @HanningtoneM,

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Invalid Code Review Request ⚠️

   - You have submitted a merged pull request, Kindly make sure you do not merge your PR until it is approved. Please make a fresh repo and resubmit your PR again.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @topeogunleye in your question so I can receive the notification.


**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

>Invalid Code Review Request **does not count** into the code reviews limit.
bmitted a merged pull request, Kindly make sure you do not merge your PR until it is approved. Please make a fresh repo and resubmit your PR again.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @topeogunleye in your question so I can receive the notification.


**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

>Invalid Code Review Request **does not count** into the code reviews limit.

**Pull request merged**
